apiVersion: v1
kind: Service
metadata:
  name: travel-api-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: travel-api
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 8443
      nodePort: {{ .Values.service.nodePort }}
